export default {
  STORE: "STORE",
  FINDNODE: "FINDNODE",
  FINDNODE_R: "FINDNODE_R",
  FINDVALUE: "FINDVALUE",
  FINDVALUE_R: "FINDVALUE_R",
  PING: "PING",
  PONG: "PONG",
  ONCOMMAND: "ONCOMMAND",
  ADD_KNODE: "ADD_KNODE",
  DISCONNECT_KNODE: "DISCONNECT_KNODE",
  BROADCAST: "BROADCAST",
  SEND: "SEND"
};
